export let productsObjList = [
  {
    title: `Dentley s Rawhide-Free 5" Retriever Sticks Dog Chew - Chicken, 10 Count`,
    animal: "Dogs",
    category: "Treats",
    description: `When you choose Dentley s Rawhide-Free Retriever Sticks with Real Chicken, you re giving your dog more than just a tasty treat. You re delivering the enticing flavor of real chicken that s nothing short of drool-worthy. `,
    price: 9.99,
    image: "https://s7d2.scene7.com/is/image/PetSmart/5299407?$CLEARjpg$",
  },
  {
    title: `All Living Things Knots & Blocks Bird Toy`,
    animal: "Bird",
    category: "Toys",
    description: `Keep your bird entertained and engaged with the All Living Things Bird Knots and Blocks Toy. This fun toy is perfect for birds who enjoy complex interaction, and rewards exploring while keeping your bird active. `,
    price: 18.99,
    image: "https://s7d2.scene7.com/is/image/PetSmart/5142324?$CLEARjpg$",
  },
  {
    title: `Fresh Step Clean Paws Calm Clumping Clay Cat Litter - Scented, Low Tracking`,
    animal: "Cats",
    category: "Litter & Litter boxes",
    description: `The low tracking cat litter you know and love, now infused with a relaxing scent. Fresh Step Clean Paws Calm cat litter features a calming scent of rose, chamomile, and natural hempseed oil for a tranquil experience in the home.`,
    price: 16.49,
    image: "https://s7d2.scene7.com/is/image/PetSmart/5312614?$CLEARjpg$",
  },
  {
    title: `All Living Things Oven Baked Cookies Papaya & Mango Flavor Bird Treat`,
    animal: "Birds",
    category: "Treats",
    description: `All Living Things Oatmeal Papaya & Mango Flavor Oven Baked Cookies are made with wholesome ingredients for an irresistible flavor and crunchy texture birds love. What a wonderfully healthy treat to serve to your feathered friend. `,
    price: 7.99,
    image: "https://s7d2.scene7.com/is/image/PetSmart/5289782?$CLEARjpg$",
  },
  {
    title: `Frontline Plus Flea & Tick Dog Treatment 45-88 lbs`,
    animal: "Dogs",
    category: "Health & Care",
    description: `Protect your dog with the #1 name in flea and tick protection. FRONTLINE Plus for Dogs Flea & Tick Large Breed Dog Spot Treatment is a fast-acting, waterproof flea and tick treatment proven to kill adult fleas, flea eggs, flea larvae, chewing lice and ticks.`,
    price: 40.99,
    image: "https://s7d2.scene7.com/is/image/PetSmart/5152706?$CLEARjpg$",
  },
  {
    title: `Lickable Treats  Squeeze Up  Cat Treats`,
    animal: "Cats",
    category: "Treats",
    description: `Lickable Treats Squeeze Ups with Tuna for cats are a new line of thick, tasty treats consisting of rich, thick purees in lickable tubes that you can hand feed to your cat for a fun and delicious treat.`,
    price: 2.49,
    image: "https://s7d2.scene7.com/is/image/PetSmart/5283720?$CLEARjpg$",
  },
  {
    title: `Merry & Bright  Holiday Cassette with Rope Stocking Stuffer Dog Toy - Squeaker`,
    animal: "Dogs",
    category: "Toys",
    description: `This Merry & Bright Cassette with Rope Stocking Stuffer Dog Toy makes a perfect gift for your pup this holiday season. This small toy comes in the form of an old school cassette player, features an attached rope, and keeps dogs entertained and engaged with the playful squeaking sounds it makes when played with.`,
    price: 1.99,
    image: "https://s7d2.scene7.com/is/image/PetSmart/5332756?$CLEARjpg$",
  },
  {
    title: `Top Paw Grey Heather X-Large Cuddler Dog Bed`,
    animal: "Dogs",
    category: "Bads & Furniture",
    description: `This Top Paw Grey Heather Core Cuddler Bed features dual layers that delicately balance softness and support. Offer your dog the comfort and support he needs to gain good rest and deep sleep with this cuddler bed for extra-large dogs. `,
    price: 62.99,
    image: "https://s7d2.scene7.com/is/image/PetSmart/5302902?$CLEARjpg$",
  },
  {
    title: `Whisker City Blue Cat Print Soft-Sided Cat Carrier`,
    animal: "Cats",
    category: "Cages",
    description: `This Whisker City Blue Floral Soft-Sided Cat Carrier makes it easy to transport your cat in comfort and style. This carrier makes it easy to load your kitty, and places an emphasis on pet comfort and stress-free travel. It also features a beautiful floral design you will love. `,
    price: 34.99,
    image: "https://s7d2.scene7.com/is/image/PetSmart/5323424?$CLEARjpg$",
  },
  {
    title: `All Living Things Silo Bird Drinker`,
    animal: "Birds",
    category: "Bowls & Feeders",
    description: `Watering your small to medium bird is easy with this All Living Things Interior Silo Drinker. This drinker is a perfect fit in most cages, and allows you to refill in easy fashion while avoiding spilling to provide water for your pet at all times. `,
    price: 5.99,
    image: "https://s7d2.scene7.com/is/image/PetSmart/5284998?$CLEARjpg$",
  },
  {
    title: `Catit 2.0 Flower Cat Drinking Fountain`,
    animal: "Cats",
    category: "Bowls & Feeders",
    description: `The Catit Flower Fountain has a fresh, unique design that allows up to 3 different water flow settings to appeal to picky drinkers! When plugged in without accessories, the Flower Fountain provides a gently flowing water surface.`,
    price: 27.99,
    image: "https://s7d2.scene7.com/is/image/PetSmart/5271613?$CLEARjpg$",
  },
  {
    title: `Whisker City 64-in Stairstep with Condo Cat Tree, White & Tan`,
    animal: "Cats",
    category: "Bads & Furniture",
    description: `Your kitty is the ruler of their kingdom, so why not give them the castle they so rightfully deserve? This Whisker City Stairstep Tall Cat Tower offers a luxuriously soft & silky abode, and features a place to perch at every turn. What better way to encourage them to climb and play all day. `,
    price: 115.49,
    image: "https://s7d2.scene7.com/is/image/PetSmart/5305280?$CLEARjpg$",
  },
  {
    title: `PetSafe Eatwell  5 Meal Automatic Pet Feeder`,
    animal: "Dogs",
    category: "Bowls & Feeders",
    description: `What a great worry-free way to make certain your pet is always fed on time. Great for portion control and establishing eating routines.`,
    price: 54.99,
    image: "https://s7d2.scene7.com/is/image/PetSmart/5115264?$CLEARjpg$",
  },
  {
    title: `Oasis Vita Drops - Small Bird`,
    animal: "Birds",
    category: "Health & Care",
    description: `Water, Ascorbic Acid, Choline chloride, Vit. A (Pallmitate) Vit. E (Dl-Alpha Tocopheryl Acetate), Niacinamide, Thiamjine Hydrochloride, Dl-Pantothenic Acid, Potassium Sorbate (Preservative0 Sodium Benzoate(Preservative) Vit. D3 (Cholecalcifferol) Riboflavin, Folic Acid, Biotin, Vit. B12 (Cyanocobalamin) Menadione (K3) Pyridoxine Hydrochloride`,
    price: 25.99,
    image: "https://s7d2.scene7.com/is/image/PetSmart/5271663?$CLEARjpg$",
  },
  {
    title: `Whisker City Natural Teaser Cat Toys - 3 Pack`,
    animal: "Cats",
    category: "Toys",
    description: `Interact with your cat while satisfying her natural instinct to hunt with this Whisker City Natural Teaser 3-pack of Cat Toys. This teaser comes with 3 catnip-infused toys to choose from. Move the wand, dangle the toy, and keep your cat active and entertained until one of you finally wears out. Only at PetSmart.`,
    price: 10.49,
    image: "https://s7d2.scene7.com/is/image/PetSmart/5287715?$CLEARjpg$",
  },
];

export let usersObjList = [
  {
    first_name: "Daniel",
    last_name: "Zegerson",
    mail: "danizeger283@gmail.com",
    psw: "450573",
    admin: true,
  },
  {
    first_name: "Moran",
    last_name: "Levi",
    mail: "mlevi@gmail.com",
    psw: "2345ML",
    admin: false,
  },
  {
    first_name: "Gil",
    last_name: "Cohen",
    mail: "gili@gmail.com",
    psw: "987654",
    admin: false,
  },
];
